# Generated by Django 3.1.6 on 2021-02-07 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='GalleryImage',
        ),
    ]
