# Generated by Django 3.1.6 on 2021-02-07 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20210207_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='image',
        ),
    ]
