# Generated by Django 3.1.6 on 2021-02-04 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_post_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='main_image',
            field=models.ImageField(default='default.jpg', upload_to='images'),
        ),
    ]
